# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tallphil.co.uk
email: phil@tallphil.co.uk
description: Articles by Phil Ewels, a bioinformatician in Stockholm, Sweden.
baseurl: "/tallphil.co.uk" # the subpath of your site, e.g. /blog
url: "https://ewels.github.io" # the base hostname & protocol for your site
twitter_username: tallphil
github_username:  ewels

# Build settings
markdown: kramdown
timezone: Europe/Stockholm
